### ISSUE TITLE
javax.naming.InitialContext.lookup() error, line 29

### ISSUE THREAD

**Issue by Fe3000** [Fe3000/Java-ChatApp#1]
Exception in thread "main" javax.naming.CommunicationException: Receive timed out [Root exception is java.net.SocketTimeoutException: Receive timed out]
        at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1630)
        at org.jnp.interfaces.NamingContext.checkRef(NamingContext.java:1759)
        at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:680)
        at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:673)
        at javax.naming.InitialContext.lookup(Unknown Source)
        at Chat.main(Chat.java:29)
Caused by: java.net.SocketTimeoutException: Receive timed out
        at java.net.TwoStacksPlainDatagramSocketImpl.receive0(Native Method)
        at java.net.TwoStacksPlainDatagramSocketImpl.receive(Unknown Source)
        at java.net.DatagramSocket.receive(Unknown Source)
        at org.jnp.interfaces.NamingContext.discoverServer(NamingContext.java:1600)
        ... 5 more

**Comment by Fe3000** [comment]
The initialisation of the context was giving the error, fixed now.
